name: Docker image build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "diwish345" --password-stdin
      
      - name: Build and Push Docker Image
        run: |
          docker build -t diwish345/fastapi-app:latest:latest .
          docker push diwish345/fastapi-app:latest:latest
